import { lazy } from "react";
import type { UIPlugin } from "@octarq/plugin-sdk";

export const twofaPlugin: UIPlugin = {
  name: "twofa",
  routes: [
    { path: "/twofa", Component: lazy(() => import("./Page")) },
  ],
  menu: [
    { id: "twofa", label: "2FA Vault", path: "/twofa", icon: "🔐", category: "Workspace" },
  ],
  i18n: {
    en: {
      pageTitle: "2FA Vault",
      pageDesc: "Centralized TOTP two-factor authentication manager for team & infrastructure accounts.",
      addAccount: "Add Account",
      editAccount: "Edit 2FA Account",
      addFirstAccount: "Add First Account",
      emptyTitle: "No 2FA accounts registered yet",
      emptyDesc: "Add your first TOTP credential to start managing shared two-factor authentication tokens.",
      searchPlaceholder: "Search by name, issuer, account, or tags...",
      filterTag: "Tag:",
      all: "All",
      copy: "Copy",
      copied: "Copied!",
      copiedToast: "Code copied to clipboard!",
      clickToCopy: "Click to copy code",
      pinned: "Pinned",
      pin: "Pin",
      unpin: "Unpin",
      pinToTop: "Pin this account to top of dashboard",
      showSecret: "Reveal Secret & QR",
      edit: "Edit",
      delete: "Delete",
      confirmDelete: "Are you sure you want to delete this 2FA account?",
      deleted: "Account deleted.",
      loading: "Loading...",
      loadingAccounts: "Loading 2FA vault accounts...",
      noMatches: "No accounts matching search criteria",
      tryDifferentSearch: "Try searching with a different term or clearing active tag filters.",
      auditLogs: "Audit Logs",
      importExport: "Import / Export",
      manualEntry: "Manual Entry",
      pasteURI: "Paste Key URI (otpauth://)",
      uriLabel: "otpauth:// URI",
      uriHelp: "Paste a provisioning URI to automatically parse the issuer, account, and secret parameters.",
      accountName: "Account Title",
      issuer: "Issuer / Service",
      username: "Account / Username / Email",
      secret: "Base32 Secret Key",
      secretEdit: "Secret Key (Leave blank to keep unchanged)",
      algorithm: "Algorithm",
      digits: "Digits",
      period: "Period (sec)",
      tags: "Tags (comma-separated)",
      notes: "Notes",
      cancel: "Cancel",
      save: "Save Account",
      saving: "Saving...",
      qrModalTitle: "QR Code & Secret",
      scanHelp: "Scan with Google Authenticator, 1Password, or any authenticator app.",
      secretSeed: "Secret Seed (Base32)",
      keyURI: "Standard Key URI",
      auditNotice: "Revealing this secret has been recorded in the workspace security audit trail.",
      close: "Close",
      auditModalTitle: "2FA Security Audit Logs",
      auditDesc: "Immutable activity history tracking every code generation, secret reveal, export, and AI agent query.",
      noLogs: "No audit events recorded yet.",
      time: "Time",
      action: "Action",
      account: "Account",
      actor: "Actor",
      ip: "IP",
      importExportTitle: "Import / Export Accounts",
      importTab: "Batch Import",
      exportTab: "Export Backup",
      pasteURIs: "Paste otpauth:// URIs (one per line)",
      importTags: "Tags to apply to all imported items",
      importing: "Importing...",
      startImport: "Start Import",
      importedSuccess: "Successfully imported",
      accounts: "accounts.",
      exportWarning: "Exported JSON contains plaintext secret URIs. Store this backup securely and never share it publicly.",
      exporting: "Exporting accounts...",
      copyJSON: "Copy JSON",
      errNameRequired: "Account name is required",
      errSecretRequired: "Secret is required",
      errInvalidURI: "URI must start with otpauth://totp/",
      errMissingSecret: "Secret is required in URI",
      errMalformedURI: "Malformed otpauth URI",
      errNoValidURIs: "No valid otpauth:// lines found.",
    },
    zh: {
      pageTitle: "2FA 密钥保管库",
      pageDesc: "集中管理团队与基础设施账户的双重验证（TOTP）密钥，提供实时动态口令与 AI Agent 自动化调用。",
      addAccount: "添加凭证",
      editAccount: "编辑 2FA 凭证",
      addFirstAccount: "添加首个凭证",
      emptyTitle: "暂未录入任何 2FA 凭证",
      emptyDesc: "添加您的第一个 TOTP 密钥，开启团队共享与智能体自动化调用。",
      searchPlaceholder: "按名称、签发方、账户或标签搜索...",
      filterTag: "标签：",
      all: "全部",
      copy: "复制",
      copied: "已复制！",
      copiedToast: "验证码已复制到剪贴板！",
      clickToCopy: "点击复制动态验证码",
      pinned: "已置顶",
      pin: "置顶",
      unpin: "取消置顶",
      pinToTop: "将此账户置顶显示在列表前列",
      showSecret: "查看密钥与二维码",
      edit: "编辑",
      delete: "删除",
      confirmDelete: "确定要删除此 2FA 凭证吗？",
      deleted: "凭证已删除。",
      loading: "加载中...",
      loadingAccounts: "正在加载 2FA 保管库数据...",
      noMatches: "没有找到匹配的 2FA 凭证",
      tryDifferentSearch: "尝试更换搜索关键词或重置标签筛选。",
      auditLogs: "审计日志",
      importExport: "导入 / 导出",
      manualEntry: "手动录入",
      pasteURI: "粘贴配置 URI (otpauth://)",
      uriLabel: "otpauth:// URI",
      uriHelp: "直接粘贴第三方服务提供的 URI，系统将自动识别签发机构、用户名及密钥。",
      accountName: "凭证名称",
      issuer: "签发机构 / 服务商",
      username: "账户 / 邮箱 / 用户名",
      secret: "Base32 密钥种子",
      secretEdit: "密钥种子（留空表示保持原有密钥不变）",
      algorithm: "散列算法",
      digits: "位数",
      period: "更新周期 (秒)",
      tags: "标签（逗号分隔）",
      notes: "备注说明",
      cancel: "取消",
      save: "保存凭证",
      saving: "保存中...",
      qrModalTitle: "二维码与密钥明文",
      scanHelp: "使用 Google Authenticator、1Password 或各类验证器扫描绑定。",
      secretSeed: "密钥明文 (Base32)",
      keyURI: "标准 Key URI",
      auditNotice: "查看或复制此密钥明文已被记录至工作区安全审计日志中。",
      close: "关闭",
      auditModalTitle: "2FA 安全审计日志",
      auditDesc: "不可篡改的安全活动轨迹，完整记录每一次口令生成、明文查看、批量导出与 AI 智能体调用。",
      noLogs: "暂无审计日志记录。",
      time: "时间",
      action: "操作",
      account: "凭证对象",
      actor: "操作主体",
      ip: "来源 IP",
      importExportTitle: "导入 / 导出 2FA 凭证",
      importTab: "批量导入",
      exportTab: "导出备份",
      pasteURIs: "粘贴 otpauth:// 链接（每行一条）",
      importTags: "应用到导入项的统一标签",
      importing: "正在导入...",
      startImport: "开始导入",
      importedSuccess: "成功导入",
      accounts: "个凭证。",
      exportWarning: "导出的 JSON 文件中包含解密后的明文密钥，请妥善保管且切勿公开分享。",
      exporting: "正在导出...",
      copyJSON: "复制 JSON",
      errNameRequired: "凭证名称不能为空",
      errSecretRequired: "密钥种子不能为空",
      errInvalidURI: "链接格式错误：必须以 otpauth://totp/ 开头",
      errMissingSecret: "URI 中缺少 secret 参数",
      errMalformedURI: "无效的 otpauth 链接",
      errNoValidURIs: "未发现有效的 otpauth:// 链接。",
    },
  },
};

export default twofaPlugin;
